#in packages if there any vulnarebility will scan
#pip audit use for python
name: Dependency Scan

on:
    workflow_call:


jobs:
    dependency-check:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v4

            - name: setup Python 3.12
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"

            - name: Install pip audit
              run : pip install pip-audit
              
            - name: audit dependency package
              run : pip-audit -r requirements.txt #scan all package mentioned in requirement txt file

          
              
    
