#Scan the docker file for issues & CVEs(common vulnarebilities and Exposures)
name: Docker Lint

on:
    workflow_call:

jobs:
    validate-dockerfile:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: validate Dockerfile
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: Dockerfile