name: Hello all
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        run: echo "Hello, Github Action"
      - name: say hello to all users
        run: echo "hello $USER"
        
  details:
    runs-on: ubuntu-latest
    steps:
         - name: daily hobbies
           run: docker --version && python --version
           
       
           
        
