name: Portfolio

on:
  push:
    branches: [main]

permissions:
      pages: write
      id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}    

    steps:
        #get acess to your portfolio code via a prebuild action by github
        #clone or checkout the code where this workflow is written
        #for every repository workflow written which works for that repository
        - name: checkout code
          uses: actions/checkout@v4
        
          #setup github pages
        - name: setup github pages
          uses: actions/configure-pages@v4
        
          #setup static pages
        - name: upload static file
          uses: actions/upload-pages-artifact@v4

          #deploy
        - name: deploy to github pages
          uses: actions/deploy-pages@v4


