name: Practice Github Action

on:
  workflow_dispatch:
   
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: get code from github
        run: echo "git clone"

   build: 
     runs-on: ubuntu-latest
     steps:
       - name: Build the code
         run: echo "Build code"

    test:
      runs-on: ubuntu-latest
      steps:
        - name: Test code
          run: echo "Test the code"

    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Deploy code
          run: echo "code successfully deployed"
          
    
    
